### ISSUE TITLE
method 3 service id property encoding/decoding

### ISSUE THREAD

**Issue by TimoGlastra** [decentralized-identity/peer-did-method-spec#39]
I'm currently implementing the peer did spec in aries framework javascript and wondering how service ids should be encoded/decoded when using method 3 did documents.

The spec mentions:

> Add id attribute according to the form
>   `#service`

It seems incomplete, or maybe I'm just not sure how to interpet this. Looking at the example did document, the id is not included in the service block before being encoded, but the decoded did document contains the service id of `#didcommmessaging-0`.

Is there a process to generate consistent ids for peer did documents?

**Comment by dhh1128** [comment]
Tagging @TelegramSam , who may have a clearer idea about the intentions of this verbiage.

**Comment by TimoGlastra** [comment]
Question answered by looking at the python peer did implementation! 

The service id should be lowercase variant of the service type + index:

```
peer_did + "#" + service_type.lower() + "-" + str(i)
```

Will try to make a PR to clarify this in the spec soon
