### ISSUE TITLE
seeking new maintainers/editors

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/peer-did-method-spec#59]
I would like to get some additional people into the maintainer role in this repo, and probably at the same time make them editors of the spec rather than simple contributors. I remain quite interested in this DID method, but I think the implementation experience of others is now surpassing my own, and I may be slowing you down.

So, is anybody interested in becoming a maintainer?

@swcurran @dbluhm @TelegramSam @TimoGlastra

**Comment by swcurran** [comment]
I’m interested, but I’m not sure about the DIF rules that would allow/prevent me from doing so.  I believe BCGov is a member. Is that sufficient?

**Comment by dhh1128** [comment]
I'm more of the "get forgiveness, not permission" mindset.
