### ISSUE TITLE
need updated regex to recognize peer DIDs

### ISSUE THREAD

**Issue by dhh1128** [decentralized-identity/peer-did-method-spec#6]
See https://github.com/openssi/peer-did-method-spec/issues/128.

@davebryson, if you are a DIF contributor, would you like to submit a PR to change the regex, so you get listed as a contributor to the spec? If not, I'm happy to make the change.

**Comment by davebryson** [comment]
@dhh1128, Hi Daniel I'm a member of `trust over ip` through my organization, but not DIF.   So it's probably not a PR I can do right away.  Probably quicker for you to make the change.  I'll look into contributing to DIF.

**Comment by dhh1128** [comment]
Fixed in #21
